### ISSUE TITLE
CMakeLists.txt improvements

### ISSUE THREAD

**Issue by ghost** [StefanoBelli/xxtelebot#16]
I would like to underline several places in CMake you can improve.

### Possible improvements
```cmake
cmake_minimum_required(VERSION 2.8)
```
* CMake 3.0 (3.6 in backports) is availiable in Debian oldstable. Maybe it's a time to finally throw away compatability and use new features?

```cmake
if(NOT CMAKE_BUILD_TYPE)
	set(CMAKE_BUILD_TYPE "Release")
endif()
```
* `CMakeLists.txt` **must not** touch CMAKE_BUILD_TYPE, this variable is part of so called "build configuration" and should be only selected by user. User may expect to get binary without optimizations and debug information (what will happen without CMAKE_BUILD_TYPE set), but you force Release mode.

```cmake
#version
set(MJVER 0)
set(MNVER 0)
set(PTVER 0)
```
* These variables will not usable outside of library's CMakeLists.txt, but you may want to allow it (in such case you may also want to rename them).
* You may also want to integrate it with Git tags, see my projects for example).
* Set version in `project()` and CMake will create `PROJECTNAME_*_VERSION` for you.

```cmake
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/lib")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/lib")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/lib")
```
* `CMAKE_*_OUTPUT_DIRECTORY` **is part of build configuration**. User may want to install/build your library in different place.
* Creating files in source tree during build is generally a bad practice. Keep everything in build directory.

```cmake
find_program(DOXYGEN_EXISTS "doxygen")
```
* CMake have `FindDoxygen` module, which can perform better in some tricky cases.

```cmake
configure_file("${HEADERS_DIR}/tgbot/version.h.in"
"${HEADERS_DIR}/tgbot/version.h")
```
* Creating files in source tree during build is generally a bad practice. Keep everything in build directory.

```cmake
message("-- Doxygen is available, use 'make docs' to generate docs")
```
* `message(STATUS)` formats your message just like CMake's.

```cmake
if(NOT LIBRARY_TYPE)
	set(LIBRARY_TYPE "static")
endif()
```
* Build configuration. Use `add_library` without explicit library type and CMake will use `BUILD_SHARED_LIBS` value, which can be easily set by user.

```cmake
find_library(JSONCPP "jsoncpp")
```
* JsonCpp provides a configuration for cmake, you can use `find_package` to import `jsoncpp_lib` target.
```
/usr/lib/cmake/jsoncpp/jsoncppConfig-release.cmake
/usr/lib/cmake/jsoncpp/jsoncppConfig.cmake
```

```cmake
if (NOT CMAKE_PREFIX_DIR AND UNIX)
	message("-- Probing prefix directory...")
	if (CMAKE_SYSTEM_NAME STREQUAL "Linux")
		set(CMAKE_PREFIX_DIR "/usr")
	else ()
		set(CMAKE_PREFIX_DIR "/usr/local")
	endif ()
	message("-- CMAKE_PREFIX_DIR=${CMAKE_PREFIX_DIR}")
endif ()
```
* **Don't touch** build configuration, it includes `CMAKE_PREFIX_DIR` too. Why you are forcing use of only `/usr/local` on non-Linux platforms?

```cmake
if(LIBRARY_TYPE STREQUAL "static")
	add_library(tgbot STATIC ${SOURCES})
	
	install(TARGETS tgbot ARCHIVE
				DESTINATION ${CMAKE_PREFIX_DIR}/lib
				PERMISSIONS OWNER_WRITE OWNER_READ OWNER_EXECUTE
				GROUP_WRITE GROUP_READ
				WORLD_READ)
else()
	add_library(tgbot SHARED ${SOURCES})
	
	install(TARGETS tgbot LIBRARY
				DESTINATION ${CMAKE_PREFIX_DIR}/lib
				PERMISSIONS OWNER_WRITE OWNER_READ OWNER_EXECUTE
				GROUP_WRITE GROUP_READ
				WORLD_READ)
endif()
```
* DRY (Don't Repeat Yourself). You can combine install command into one statement, also there is no need to explicitly specify permissions. So...
  ```cmake
  install(TARGETS tgbot 
  LIBRARY DESTINATION /lib
  ARCHIVE DESTINATION /lib)
  ```
  P.S. Destination is relative to prefix, so no need to specify it explicitly.

```cmake
set(CMAKE_CXX_STANDARD 11)
```
* This variable is supported only since CMake 3.2. Anyways, you may want to add `CMAKE_CXX_STANDARD_REQUIRED=ON` and `CMAKE_CXX_STANDARD_EXTENSIONS=OFF`.

```cmake
include_directories(${HEADERS_DIR} ${OTHER_HDR_DIR})
```
* IMO, `HDR` is pretty weird abbreviation of "header".
* You may want to set include directories for target to allow using it by just adding `target_link_libraries`.

### Notes
* [This repository](https://github.com/ttroy50/cmake-examples) have a lot of useful examples.
* [This one](https://github.com/foxcpp/Hexicord/blob/v0.3.0/CMakeLists.txt) is a good example of CMake materpiece :P.

**Comment by StefanoBelli** [comment]
For some points, (such as the prefix dir), if user specifies it, the build system won't touch that.

Anyway I would appreciate if you make me a pull request, so you'll be enlisted in contributors, if you want :).

I'll keep this open, thanks for being interested and suggestions!

EDIT: you're right for the install statement, lol, I just wanted to use different add_library configuration.

**Comment by StefanoBelli** [comment]
Closing issue, ref commit 30c4753
