### ISSUE TITLE
Function sendAudio send a Voice Message

### ISSUE THREAD

**Issue by Ismaw34** [StefanoBelli/xxtelebot#32]
Hello,

Since couple of months the api sends VoiceMessages (like sendVoice) but using sendAudio.

**Comment by StefanoBelli** [comment]
It shouldn't, I'll test ASAP

**Comment by Ismaw34** [comment]
I tested it, again with other audio codec. When sending audios with the codec ogg, telegram treats them as voice. Tested it again with mp3, sent audio this time. I think its more a server side not an api problem. Thanks.

**Comment by StefanoBelli** [comment]
Definitively it is, this API will forward the mime type without touching it in any way. 

Thanks for using this API wrapper :)
